<a href="https://colab.research.google.com/github/Mvinachi/Hyperblog/blob/main/Creando_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
matriz = np.zeros((10,10))
print(matriz)
matriz.ndim

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


2

In [ ]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand()

0.6458511673675986

In [ ]:
np.random.rand(4)

array([0.14663108, 0.19487453, 0.99284232, 0.23577687])

In [ ]:
np.random.rand(4,4)

array([[0.18952936, 0.70806969, 0.42056754, 0.75036959],
       [0.63140961, 0.63711517, 0.44736551, 0.14402328],
       [0.43846733, 0.67974896, 0.61154206, 0.29927248],
       [0.89449054, 0.86265728, 0.48442129, 0.5712004 ]])

In [ ]:
np.random.randint(1,15)

13

In [ ]:
np.random.randint(1,100,(10,10))

array([[69, 58, 69, 48, 36, 75, 20, 35, 22, 92],
       [91, 52, 13, 21, 13, 16, 40, 56, 27,  6],
       [24, 67, 99, 19, 79, 85, 49, 84, 81, 60],
       [99, 40, 72, 56, 27, 41, 38, 42,  7, 50],
       [54, 56, 99, 74, 95, 46, 71, 81, 50, 27],
       [31, 32, 10, 59, 81, 65,  6, 88, 25, 31],
       [45, 40, 24, 26, 40, 44, 35,  4, 29,  8],
       [45, 27, 53, 14, 13, 87, 92, 12,  2, 94],
       [68, 87, 19, 52, 80, 48, 84, 74, 71, 35],
       [37, 42,  1, 50, 48, 22, 47, 27, 61, 69]])