<a href="https://colab.research.google.com/github/Mvinachi/Hyperblog/blob/main/Funciones_principales_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,20,10)

In [ ]:
matriz = arr.reshape(2,5)
matriz

array([[10,  6, 13, 10, 10],
       [16, 13, 10,  7,  8]])

In [ ]:
arr

array([10,  6, 13, 10, 10, 16, 13, 10,  7,  8])

In [ ]:
arr.max()

16

In [ ]:
matriz

array([[10,  6, 13, 10, 10],
       [16, 13, 10,  7,  8]])

Mayores por columna

In [ ]:
matriz.max(0)

array([16, 13, 13, 10, 10])

mayores por fila

In [ ]:
matriz.max(1)

array([13, 16])

In [ ]:
arr.argmax()

5

In [ ]:
matriz.argmax()

5

In [ ]:
matriz.argmax(0)

array([1, 1, 0, 0, 0])

In [ ]:
matriz.argmax(1)

array([2, 0])

In [ ]:
vector = np.arange(1,11)
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_vector = vector[0:6]
slice_of_vector

array([1, 2, 3, 4, 5, 6])

In [ ]:
copy_of_slice = np.copy(slice_of_vector)
copy_of_slice

array([1, 2, 3, 4, 5, 6])

In [ ]:
copy_of_slice[:] = 0
print(vector)
print(slice_of_vector)
print(copy_of_slice)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 6]
[0 0 0 0 0 0]
