<a href="https://colab.research.google.com/github/Mvinachi/Hyperblog/blob/main/Shape_and_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,2))

In [3]:
arr.shape

(3, 2)

In [4]:
arr

array([[6, 5],
       [3, 1],
       [6, 9]])

In [8]:
reshaped = arr.reshape(1,6)
print(reshaped)
reshaped.ndim

[[6 5 3 1 6 9]]


2

In [12]:
reshaped_v2 = arr.reshape(2,3)
print(reshaped_v2)
reshaped_v2.ndim

[[6 5 3]
 [1 6 9]]


2

In [13]:
np.reshape(arr,(6,1))

array([[6],
       [5],
       [3],
       [1],
       [6],
       [9]])

In [15]:
np.reshape(arr,(2,3), 'C')

array([[6, 5, 3],
       [1, 6, 9]])

In [16]:
np.reshape(arr,(2,3), 'F')

array([[6, 6, 1],
       [3, 5, 9]])

In [17]:
np.reshape(arr,(2,3), 'A')

array([[6, 5, 3],
       [1, 6, 9]])